name: __MSG_extName__
description: __MSG_extDescription__
author: Rosco Pecoltran <rosco_pecoltran@msn.com>
version: 1.0.0
icons:
  '16': icons/16.png
  '128': icons/128.png
permissions:
  - activeTab
  - tabs
  - background
  - unlimitedStorage
  - storage
  - downloads
  - bookmarks
  - topSites
  - nativeMessaging
  - unlimitedStorage
  - contextMenus
  - cookies
  - webNavigation
  - notifications
  - tabCapture
  - webRequestBlocking
  - clipboardWrite
  - clipboardRead
  - 'http://github.com/'
  - 'https://github.com/'
  - 'https://libraries.io/api/'
  - 'http://localhost:3000/api/'
  - 'https://localhost:3000/api/'
  - 'chrome://favicon/'
  - 'http://*/*'
  - 'https://*/*'
  - '*://github.com/*'
  - '*://api.github.com/*'
  - 'https://assets-cdn.github.com/*'
  - 'https://camo.githubusercontent.com/*'
chrome_url_overrides:
  newtab: pages/app.html
browser_action:
  default_title: title
  default_popup: pages/popup.html
commands:
  add_to_queue:
    suggested_key:
      default: Alt+Q
      mac: Alt+Q
    description: Add Current page to Queue
  add_to_bookmarks:
    suggested_key:
      default: Alt+B
      mac: Alt+B
    description: Add Current page to Bookmarks
background:
  persistent: false
  page: pages/background.html
devtools_page: pages/devtools.html
options_page: pages/options.html
content_scripts:
  - run_at: document_idle
    matches:
      - 'https://github.com/*'
    all_frames: false
    js:
      - js/manifest.js
      - js/vendor.js
      - js/0.0.js
      - js/1.1.js
      - js/10.10.js
      - js/11.11.js
      - js/12.12.js
      - js/13.13.js
      - js/14.14.js
      - js/15.15.js
      - js/16.16.js
      - js/2.2.js
      - js/25.25.js
      - js/3.3.js
      - js/4.4.js
      - js/5.5.js
      - js/6.6.js
      - js/7.7.js
      - js/8.8.js
      - js/9.9.js
      - js/content.js
    css:
      - css/content.94483f0e6524b330f04599052915d2f7.css
default_locale: en
manifest_version: 2
content_security_policy: >-
  script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src
  'self'; font-src 'self'; object-src 'self'
web_accessible_resources:
  - panel.html
  - icons/*.*
  - img/*.*
  - fonts/*.*
  - css/*.*
  - js/content.js
