/**
 *  本地存储的键
 */
const Keys = {
  // featrues key
  BACKGROUND: 'BACKGROUND',
  ENGINE: 'ENGINE',
  LOVESITES: 'LOVESITES',
  // setting key
  SETTING_APPLICATION: 'SETTING_APPLICATION',
  SETTING_BOOKMARK: 'SETTING_BOOKMARK',
  SETTING_COMMONSITES: 'SETTING_COMMONSITES',
  // bakcground
  SETTING_BING: 'SETTING_BING',
  SETTING_COLOR: 'SETTING_COLOR'
  // top sites
  SETTING_TOP_SITES: 'SETTING_TOP_SITES',
  SETTING_TOP_SITE: 'SETTING_TOP_SITE',
  SETTING_TOP_CONFIG: 'SETTING_TOP_CONFIG'
}

export default Keys
